2025-05-25 23:08:51,092 ERROR: Exception on /reset_password_request [POST] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\myblog\app\routes.py", line 203, in reset_password_request
    send_password_reset_email(user)
  File "D:\myblog\app\email.py", line 22, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token))
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\myblog\app\templates\email\reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\myblog\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "D:\myblog\app\templates\email\reset_password.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-05-25 23:11:55,176 INFO: Myblog startup [in D:\myblog\app\__init__.py:62]
2025-05-25 23:12:03,080 ERROR: Exception on /reset_password_request [POST] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\myblog\app\routes.py", line 203, in reset_password_request
    send_password_reset_email(user)
  File "D:\myblog\app\email.py", line 22, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token))
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\myblog\app\templates\email\reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\myblog\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "D:\myblog\app\templates\email\reset_password.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-05-25 23:20:02,853 INFO: Myblog startup [in D:\myblog\app\__init__.py:62]
2025-05-25 23:20:12,599 ERROR: Exception on /reset_password_request [POST] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\myblog\app\routes.py", line 203, in reset_password_request
    send_password_reset_email(user)
  File "D:\myblog\app\email.py", line 24, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token))
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\myblog\app\templates\email\reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\myblog\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "D:\myblog\app\templates\email\reset_password.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-05-25 23:21:31,431 INFO: Myblog startup [in D:\myblog\app\__init__.py:62]
2025-05-25 23:21:39,316 ERROR: Exception on /reset_password_request [POST] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\myblog\app\routes.py", line 203, in reset_password_request
    send_password_reset_email(user)
  File "D:\myblog\app\email.py", line 24, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token))
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\myblog\app\templates\email\reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\myblog\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "D:\myblog\app\templates\email\reset_password.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-05-25 23:23:37,948 INFO: Myblog startup [in D:\myblog\app\__init__.py:62]
